In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
df=pd.read_csv(r'D:\programming\coding\dataset\newobs.csv')
df.head()
print(df['NObeyesdad'].value_counts())

NObeyesdad
Obesity_Type_III       4046
Obesity_Type_II        3248
Normal_Weight          3082
Obesity_Type_I         2910
Insufficient_Weight    2523
Overweight_Level_II    2522
Overweight_Level_I     2427
Name: count, dtype: int64


In [3]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()
df.loc[:,'Gender']=lr.fit_transform(df.loc[:,'Gender'])
df.loc[:,'family_history_with_overweight']=lr.fit_transform(df.loc[:,'family_history_with_overweight'])
df.loc[:,'FAVC']=lr.fit_transform(df.loc[:,'FAVC'])
df.loc[:,'CAEC']=lr.fit_transform(df.loc[:,'CAEC'])
df.loc[:,'SMOKE']=lr.fit_transform(df.loc[:,'SMOKE'])
df.loc[:,'SCC']=lr.fit_transform(df.loc[:,'SCC'])
df.loc[:,'CALC']=lr.fit_transform(df.loc[:,'CALC'])
df.loc[:,'MTRANS']=lr.fit_transform(df.loc[:,"MTRANS"])
df.loc[:,'NObeyesdad']=lr.fit_transform(df.loc[:,'NObeyesdad'])
df['NObeyesdad']=df['NObeyesdad'].astype('float64')


In [4]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
y=y.reshape(-1,1)

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
x_test.shape


(6228, 17)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)
print(y_train)

(14530, 17) (6228, 17) (14530, 1) (6228, 1)
[[3.]
 [6.]
 [0.]
 ...
 [0.]
 [4.]
 [6.]]


In [7]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=17,activation='relu'))
ann.add(tf.keras.layers.Dense(units=22,activation='relu'))
ann.add(tf.keras.layers.Dense(units=7,activation='softmax'))
ann.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
ann.fit(x_train,y_train,batch_size=32,epochs=150)

Epoch 1/150
455/455 [==============================] - 2s 2ms/step - loss: 1.2407 - accuracy: 0.5238
Epoch 2/150
455/455 [==============================] - 1s 2ms/step - loss: 0.6468 - accuracy: 0.7479
Epoch 3/150
455/455 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.8149
Epoch 4/150
455/455 [==============================] - 1s 2ms/step - loss: 0.4519 - accuracy: 0.8381
Epoch 5/150
455/455 [==============================] - 1s 2ms/step - loss: 0.4277 - accuracy: 0.8481
Epoch 6/150
455/455 [==============================] - 1s 2ms/step - loss: 0.4149 - accuracy: 0.8543
Epoch 7/150
455/455 [==============================] - 1s 2ms/step - loss: 0.4052 - accuracy: 0.8579
Epoch 8/150
455/455 [==============================] - 1s 2ms/step - loss: 0.3997 - accuracy: 0.8616
Epoch 9/150
455/455 [==============================] - 1s 2ms/step - loss: 0.3935 - accuracy: 0.8637
Epoch 10/150
455/455 [==============================] - 1s 2ms/step - loss: 0.3885 - accura

In [15]:
l=ann.predict(x_train,y_train)
y_pred=np.argmax(l,axis=1)
print(y_pred)


[4 5 1 ... 3 5 3]


In [9]:
df['NObeyesdad'].unique()

array([6., 1., 0., 4., 3., 5., 2.])

In [10]:
df1=df.copy()

In [11]:
df1=pd.read_csv(r'D:\programming\coding\dataset\newobs.csv')
classes=list(df1['NObeyesdad'].unique())

In [12]:
pred_classes=[]
for i in list(y_pred):
    pred_classes.append(classes[i])



In [13]:
print(pred_classes)

['Obesity_Type_II', 'Overweight_Level_I', 'Normal_Weight', 'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_III', 'Obesity_Type_II', 'Normal_Weight', 'Obesity_Type_III', 'Normal_Weight', 'Normal_Weight', 'Obesity_Type_II', 'Normal_Weight', 'Normal_Weight', 'Overweight_Level_I', 'Obesity_Type_II', 'Obesity_Type_II', 'Obesity_Type_II', 'Obesity_Type_I', 'Normal_Weight', 'Insufficient_Weight', 'Normal_Weight', 'Normal_Weight', 'Obesity_Type_II', 'Insufficient_Weight', 'Insufficient_Weight', 'Obesity_Type_I', 'Normal_Weight', 'Obesity_Type_I', 'Overweight_Level_II', 'Insufficient_Weight', 'Obesity_Type_III', 'Insufficient_Weight', 'Overweight_Level_I', 'Insufficient_Weight', 'Overweight_Level_I', 'Insufficient_Weight', 'Obesity_Type_III', 'Overweight_Level_II', 'Insufficient_Weight', 'Normal_Weight', 'Obesity_Type_III', 'Obesity_Type_II', 'Normal_Weight', 'Normal_Weight', 'Obesity_Type_II', 'Obesity_Type_III', 'Obesity_Type_III', 'Normal_Weigh

In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,y_test))

0.869942196531792
